os: Visual Studio 2015
platform: x64
environment:
  matrix:
    - nodejs_version: "18"
    - nodejs_version: "16"
    - nodejs_version: "14"
    - nodejs_version: "12"
    - nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - yarn install

test_script:
  - node --version
  - yarn --version
  - yarn test

build: off
deploy: off
